language: cpp

matrix:
  include:
    - os: osx

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install antlr
      brew install antlr4-cpp-runtime
      brew install fish
      brew install llvm
      brew install ninja
    fi

script:
  - make configure run
